cargo-features = ["profile-rustflags"]

[package]
name = "appsomethinggggg123456432"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.0.3", features = ["protocol-asset"] }
tauri-plugin-fs = "2.0.0"
tauri-plugin-http = "2.0.0"
tauri-plugin-log = "2.0.0-rc"
tauri-plugin-os = "2.0.0"
tauri-plugin-opener = "2"
embed_anything = {git = "https://github.com/StarlightSearch/EmbedAnything.git", branch = "make-features", default-features=false}
tokio = { version = "1", features = ["macros", "rt-multi-thread"] } #added for async
anyhow = "1" #add this

[profile.dev]
rustflags = ["-C", "target-feature=+fp16,+fhm"]
